name: Generate GitHub Issues HTML Page

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      label:
        type: string
        required: false
        default: good first issue
      language:
        type: string
        required: false
        default: java
      stars:
        type: number
        required: false
        default: 1
      limit:
        type: number
        required: false
        default: 100

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt

    - name: Run the GitHub Issues script
      run: |
        echo "Running with label: ${{ inputs.label }}, language: ${{ inputs.language }}, stars: ${{ inputs.stars }}, limit: ${{ inputs.limit }}"
        python src/app.py --label "${{ inputs.label || 'good first issue' }}" --language "${{ inputs.language || 'java' }}" --stars "${{ inputs.stars || 1 }}" --limit "${{ inputs.limit || 500 }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate-html

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
